site_name: 'Haldayne PHP Componentry'
pages:
- 'About Haldayne': 'index.md'
-  Haldayne\Boost:
   - 'Introduction': 'boost/index.md'
-  Haldayne\Fox:
   - 'Introduction': 'fox/index.md'
   - 'Class design and advantages of higher order functions': 'fox/design-and-advantage.md'
   - 'List of implemented generic functions': 'fox/list-of-generic-functions.md'
